global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'federate-aidev01'
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
        - '{__name__=~"up"}'
        - '{__name__=~"node_.*"}'
        - '{__name__=~"http_.*"}'
        - '{__name__=~"container_.*"}'
    static_configs:
      - targets:
          - '10.69.69.9:9090'
        labels:
          environment: 'aidev01'

  - job_name: 'federate-aiqa01'
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
        - '{__name__=~"up"}'
        - '{__name__=~"node_.*"}'
        - '{__name__=~"http_.*"}'
        - '{__name__=~"container_.*"}'
    static_configs:
      - targets:
          - '10.69.69.10:9090'
        labels:
          environment: 'aiqa01'
